### ISSUE TITLE
command not found: flocli

### ISSUE THREAD

**Issue by slavakurilyak** [dylanintech/flo#1]
After installing flocli via `$ npm i -g flocli` I am unable to configure it via `$ flocli configure`.

I tried uninstalling and installing again but I'm still seeing the same issue.

**Comment by dylanintech** [comment]
@slavakurilyak thanks for raising this issue. that's very odd. have you tried running `npm i flocli` rather than `npm i -g flocli`?

this might be an issue with global installation.

if this ^ does not work feel free to drop a screenshot or copy + paste whatever log you're getting so that i can try to fix this as soon as possible!

**Comment by dylanintech** [comment]
> After installing flocli via `$ npm i -g flocli` I am unable to configure it via `$ flocli configure`.
> 
> I tried uninstalling and installing again but I'm still seeing the same issue.

so there's actually no issue with the package, i accidentally wrote the wrong command in the `README`, the correct command (after globally installing the package with the `-g` flag) would be `flo configure`, not `flocli configure`.

confusing, i know.

also my comment here about installing the cli tool without the `-g` flag is incorrect, the package must be installed globally for the commands to work - just make sure to use `flo` at the beginning of every command rather than `flocli` as outlined in the updated `README`.

sorry about that @slavakurilyak and any others that experienced this issue, at least it was just a silly typo in the `README` and not a real problem with the code, i was worried for a second there!
